### ISSUE TITLE
fixing the UI of my dashboard

### ISSUE THREAD

**Issue by Sweata1403** [Sweata1403/React-Admin-Dashboard-App_hacktoberfest2024#1]
So in this project of mine, I am unable to fix the UI of my sidebar.
That is when you scroll down, you can see the main page is getting scrolled but there is blank space just below the sidebar which is fixed.
The page needs to be fitted in with both the main and the sidebar. 
Any help from you guys would be appreciated:
![Uploa
![Screenshot (742)](https://github.com/user-attachments/assets/d958b89a-c6c7-4c89-8983-0fa7fca9af5e)
ding image.png…]()

**Comment by Sapna127** [comment]
hey, I would like to work on this issue please assign it to me.

**Comment by PRAteek-singHWY** [comment]
@Sweata1403 please assign this issue to me i would love to work on this .

**Comment by Sweata1403** [comment]
Hey i will assign you this very soon. Just give me some time now
