### ISSUE TITLE
Fix the bug of the sidebar photo

### ISSUE THREAD

**Issue by Sweata1403** [Sweata1403/React-Admin-Dashboard-App_hacktoberfest2024#3]
I am facing an issue. after collapsing the sidebar, the image gets broken as shown in the picture:
![image](https://github.com/user-attachments/assets/567287eb-57a5-42e6-b15d-56d21ecb03e8)

help me to fix this UI

**Comment by PRAteek-singHWY** [comment]
@Sweata1403  iSir,  solved up this bug , but i am unable to make a PR can u please help with that

**Comment by PRAteek-singHWY** [comment]
here ma'am this is the issue which you closed but didn't merged .
ma'am i know u r busy so please when u are free , i request you to  look into this .
and merge it with hacktoberfest tag , so that it could be counted towards my Hacktoberfest PRs .
Thank You
